create table TB_ANIMAL (
codigo bigint generated by default as identity,
ID_CLIENTE bigint,
data_nascimento DATE,
especie VARCHAR2(10),
nome VARCHAR2(100),
ID_UNIDADE BIGINT,
primary key (codigo));

CREATE TABLE TB_CLIENTE (
 ID BIGINT generated by default as identity,
 NOME_CLIENTE VARCHAR2(100),
 CPF_CLIENTE VARCHAR2(14),
 INADIMPLENTE BOOLEAN,
 ID_UNIDADE BIGINT,
primary key (ID)
);

CREATE TABLE TB_UNIDADE (
    ID BIGINT generated by default as identity,
    NOME VARCHAR2(100),
    ENDERECO VARCHAR2(300),
    primary key (ID)
);

CREATE TABLE TB_PRODUTO (
    ID BIGINT generated by default as identity,
    VALOR NUMBER(8,2),
    DESCRICAO VARCHAR2(300),
    ID_ANIMAL BIGINT,
    primary key (ID)
);

alter table TB_ANIMAL add constraint FK_ANIMAL_UNIDADE
foreign key (ID_UNIDADE) references TB_UNIDADE;

alter table TB_CLIENTE add constraint FK_CLIENTE_UNIDADE
foreign key (ID_UNIDADE) references TB_UNIDADE;

alter table TB_PRODUTO add constraint FK_PRODUTO_ANIMAL
foreign key (ID_ANIMAL) references TB_ANIMAL;
